"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from './Provider'
import HeaderNavBar from "./components/HeaderNavBar";
import { useEffect, useState } from "react";
import Home from "./page";
import { UserLocationContext } from "@/context/UserLocationContext";
import {SelectedPandalsContext} from "@/context/SelectedPandalsContext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const[userLocation, setUserLocation]=useState([]);
  const [selectedPandals, setSelectedPandals] = useState([]);


 
  

  const getUserLocation = ()=>{
    navigator.geolocation.getCurrentPosition(function(pos){
      console.log(pos)
      setUserLocation({
        lat:pos.coords.latitude,
        lng:pos.coords.longitude
      })
    })
  };

   useEffect(() => {
     getUserLocation();
   }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <SelectedPandalsContext.Provider value={{selectedPandals, setSelectedPandals}}>
            <UserLocationContext.Provider
              value={{ userLocation, setUserLocation }}
            >
              <HeaderNavBar />
              {children}
            </UserLocationContext.Provider>
          </SelectedPandalsContext.Provider>
        </Provider>
      </body>
    </html>
  );
}
